-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc/LoRaWAN_withoutGolay/LoRaWAN_withoutGolay.vhd
-- Created: 2021-05-25 01:55:35
-- 
-- Generated by MATLAB 9.10 and HDL Coder 3.18
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 0.001024
-- Target subsystem base rate: 0.001024
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: LoRaWAN_withoutGolay
-- Source Path: LoRaWAN_withoutGolay
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY LoRaWAN_withoutGolay IS
END LoRaWAN_withoutGolay;


ARCHITECTURE rtl OF LoRaWAN_withoutGolay IS

BEGIN
  -- Transmitter
  -- 
  -- Receiver

END rtl;

