-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc/LoRaWAN_withGolay/LoRaWAN_withGolay.vhd
-- Created: 2021-05-25 01:59:32
-- 
-- Generated by MATLAB 9.10 and HDL Coder 3.18
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 0.001024
-- Target subsystem base rate: 0.001024
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: LoRaWAN_withGolay
-- Source Path: LoRaWAN_withGolay
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY LoRaWAN_withGolay IS
END LoRaWAN_withGolay;


ARCHITECTURE rtl OF LoRaWAN_withGolay IS

BEGIN
  -- Transmitter
  -- 
  -- Receiver

END rtl;

